# Site Settings
title: NaraeKim
email: rlaskfoys90@gmail.com
description: Data
baseurl: 
url: 
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: NaraeKim
user_description: Data Scientist
disqus_username: rlaskfo

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
